unique_ids:
  forms:
    mainpage: JGHL3Q23O7SPUWASPFC2RTOKM7WL5EAM
    mainpage.ItemTemplate1: '1675875055901348452367098.79425'
  modules: {}
  server_modules:
    get_content: '1675107121071968968569886.7318'
  assets:
    standard-page.html: MKXYSDI5B3I6EA4OVDL7HJYSHI4IO674
    theme.css: BEIW3JBPXL3WCUDSIVVNFHKH6JXMWJAC
